name: cd

on:
  push:
    branches:
      - "master"

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Install yarn and dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build